Add tokens list
Emurgo/yoroi-frontend pull request #2301
Opened 2021-08-11 13:51 UTC by AhmedIbrahim336

![tokenlist](https://user-images.githubusercontent.com/72753578/129041135-61a6f54b-8168-4490-8ba5-f1e8360b92a8.png)

@Marta-Ryzhok  Feel free to request changes

2021-08-13 11:35 UTC, Marta-Ryzhok commented
@AhmedIbrahim336 
if there is 50 type of tokens it will be listed below the input?

2021-08-23 10:42 UTC, AhmedIbrahim336 commented
> if there is 50 type of tokens it will be listed below the input?
@Marta-Ryzhok Feel free to suggest another option

2021-08-26 09:25 UTC, yushih requested changes
I think there's a problem: if I select a token and select "send all", then I'm only sending this token so it should not show the token list, but it does:
![tokenlist](https://user-images.githubusercontent.com/1028789/130937955-2495897f-8d79-402e-b513-d824073efa10.jpg)

2021-08-26 09:25 UTC, yushih commented on packages/yoroi-extension/app/components/wallet/send/WalletSendForm.js
> +           this.form.$('selectedAmount').value === tokenId
Should this be `this.form.$('selectedToken').value === tokenId` ?

2021-08-26 09:25 UTC, yushih commented on packages/yoroi-extension/app/components/wallet/send/WalletSendForm.js
> +              <p key={token.id} className= "accordion-item__paragraph" >
What is the class `accordion-item__paragraph` for? Seems there's no style that applies to this class.

Also please fix the indentation.

2021-08-26 10:23 UTC, Marta-Ryzhok commented
> I think there's a problem: if I select a token and select "send all", then I'm only sending this token so it should not show the token list, but it does:
> ![tokenlist](https://user-images.githubusercontent.com/1028789/130937955-2495897f-8d79-402e-b513-d824073efa10.jpg)

Yeah you’re right, shouldn’t be a token list below

2021-08-27 07:53 UTC, neuodev commented on packages/yoroi-extension/app/components/wallet/send/WalletSendForm.js
> +              <p key={token.id} className= "accordion-item__paragraph" >
I replaced it 👍

2021-09-04 02:23 UTC, yushih requested changes
In the last commit, 3 irrelevant `package-lock.json` files are checked in. Please remove the changes. Otherwise LGTM.

2021-09-08 04:19 UTC, yushih commented
@AhmedIbrahim336, please resolve the conflict.

2021-09-08 04:20 UTC, yushih requested changes
@AhmedIbrahim336 , please resolve the conflict.

2021-09-08 14:11 UTC, neuodev commented
@yushih  Done

2021-09-09 16:45 UTC, yushih commented
/check

2021-09-09 16:45 UTC, yushih approved these changes

2021-09-10 02:02 UTC, merged