Remove Zero Decimals From Yoroi
Emurgo/yoroi-frontend pull request #2418
Opened 2021-09-27 08:52 UTC by AhmedIbrahim336

Complete task information available on [asana](https://app.asana.com/0/1200458692294040/1200897469103929/f)

Uploading Screen Recording 2021-09-27 at 10.46.47 AM.mov…

2021-09-29 15:57 UTC, yushih requested changes

2021-09-29 15:57 UTC, yushih commented on packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
> +      // const displayAmount = shiftedAmount.toFormat(tokenInfo.Metadata.numberOfDecimals)
please don't leave commented-out lines in the code

2021-09-29 15:57 UTC, yushih commented on packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
> +         {/* {displayAmount} */}
please remove this line

2021-09-29 15:57 UTC, yushih commented on packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
> +          <span>{afterDecimalRewards}</span>
please remove `.afterDecimal` from the scss file

2021-09-29 15:57 UTC, yushih commented on packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
> +          <span>{afterDecimalRewards}</span>
Also, since we are displaying the parts before and after the decimal point with the same font now, can we not split the amount? It is confusing.

2021-09-29 15:57 UTC, yushih commented on packages/yoroi-extension/app/utils/formatters.js
> +export const removeZeros: (string => string) = (amount: string): string => {
Please don't export this function, unless it is used by other modules.

2021-09-29 15:57 UTC, yushih commented on packages/yoroi-extension/app/utils/formatters.js
> +  if (Number(afterDecimal) === 0) {
why not test if `afterDecimal === ''`?

2021-09-29 15:57 UTC, yushih commented on packages/yoroi-extension/app/utils/formatters.js
> +  return [beforeDecimal, afterDecimal]
Note when `amount` is `new BigNumber('1')` and `decimalPlaces` is `0`, this function outputs `['', '']`, but it should output `['1', '']`. Please fix and add a test file `formatters.test.js` to test it.

2021-09-29 15:57 UTC, yushih commented on packages/yoroi-extension/app/utils/formatters.js
> +export const removeZeros: (string => string) = (amount: string): string => {
The purpose of this function is to remove trailing zeros? Then you can simpily do:
`return amount.replace(/0+$/, '')`

2021-09-29 15:57 UTC, yushih commented on packages/yoroi-extension/app/utils/formatters.js
> +export const amountWithoutZeros: (string => string) = (amount: string): string => {
`return amount.replace(/0+$/, '')..replace(/\.$/, '')` would do

2021-10-07 08:01 UTC, neuodev commented on packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
> +          <span>{afterDecimalRewards}</span>
I got your point. The reason why we are still splitting the amount is the `splitAmount` function has the logic to remove the zeros. Also, In the dashboard page we are still displaying the decimal points in smaller fonts

2021-10-07 08:04 UTC, neuodev commented on packages/yoroi-extension/app/utils/formatters.js
> +export const removeZeros: (string => string) = (amount: string): string => {
Awesome 👏

2021-10-07 08:06 UTC, neuodev commented on packages/yoroi-extension/app/utils/formatters.js
> +  if (Number(afterDecimal) === 0) {
Because
```js
Number('') // 0 
// Also 
Number(' ') // 0 
```
Any way I just update it to 

```js
if (!afterDecimal) {
 // 
} 
```

2021-10-07 08:17 UTC, neuodev commented on packages/yoroi-extension/app/utils/formatters.js
> +  return [beforeDecimal, afterDecimal]
I just run this test case and it passed 
```js 
test('Should return only integer of no decimals', () => {
    const amount = new BigNumber('1')
    const [before, after] = splitAmount(amount, 5)
    expect(before).toBe('1')
    expect(after).toBe('')
})
```

2021-10-11 08:47 UTC, yushih requested changes
`splitAmount` is wrong when `decimalPlaces` is `0` (which could happen for some tokens)
This test fails:
```
test('splitAmount with 0 decimal place', () => {
    const amount = new BigNumber('1')
    const [before, after] = splitAmount(amount, 0)
    expect(before).toBe('1')
    expect(after).toBe('')
})
```

2021-10-11 08:48 UTC, yushih commented on packages/yoroi-extension/app/utils/formatters.js
> +  return [beforeDecimal, afterDecimal]
Please note this test doesn't cover the case where `decimalPlaces` is `0`.

2021-10-11 08:49 UTC, yushih commented on packages/yoroi-extension/app/utils/formatters.js
> +  if (Number(afterDecimal) === 0) {
Make sense.

2021-10-28 10:29 UTC, yushih commented
/check

2021-10-28 10:30 UTC, yushih approved these changes

2021-10-28 15:30 UTC, yushih approved these changes

2021-10-28 15:34 UTC, merged