Move the locked asset deposit value to the "Assets" page
Emurgo/yoroi-frontend pull request #2422
Opened 2021-09-28 11:30 UTC by AhmedIbrahim336

The looked amount is now on the assets page. Will only be displayed for Cardano. 

<img width="1288" alt="Screen Shot 2021-09-28 at 1 28 24 PM" src="https://user-images.githubusercontent.com/72753578/135078519-5346ce0f-0a3e-4d4a-b4ee-ed2245f4cae1.png">
<img width="1288" alt="Screen Shot 2021-09-28 at 1 28 34 PM" src="https://user-images.githubusercontent.com/72753578/135078540-47446537-592c-403b-a5dc-6560d0ee38e6.png">

2021-10-04 05:09 UTC, yushih requested changes
LGTM expect for some style problems.

2021-10-04 05:09 UTC, yushih commented on packages/yoroi-extension/app/containers/wallet/WalletAssetsPage.js
> +    return (
Please fix indentations.

2021-10-04 05:09 UTC, yushih commented on packages/yoroi-extension/app/components/wallet/assets/AssetsList.js
> +    shouldHideBalance: boolean,
Please either access all 3 parameters from `this.props`, or pass them all as parameters.

2021-10-04 05:09 UTC, yushih commented on packages/yoroi-extension/app/components/wallet/assets/AssetsList.js
> +      let balanceDisplay;
Please fix indentations.

2021-10-12 15:28 UTC, yushih commented
/check

2021-10-12 15:29 UTC, yushih approved these changes

2021-10-12 20:28 UTC, zuzunker approved these changes

2021-10-13 01:46 UTC, merged