Redesign dapp connector 2
Emurgo/yoroi-frontend pull request #2631
Opened 2022-01-04 18:03 UTC by paulclindo

TODO: 
[ ] Support for Signin Cardano
[ ] Details Tab Page Redesign

Overview Tab
![CleanShot 2022-01-04 at 12 50 54@2x](https://user-images.githubusercontent.com/46382556/148103406-65cf5ef5-bb63-4a1e-b033-96ed157ba668.png)

2022-02-28 08:34 UTC, AhmedIbrahim336 commented on packages/yoroi-extension/app/ergo-connector/components/signin/CardanoSignTxPage.js
> +              ) : null}
We should display a placeholder image.We already have this in the connected websites screen in Yoroi 
[check this ](https://github.com/Emurgo/yoroi-frontend/blob/develop/packages/yoroi-extension/app/components/dapp-connector/ConnectedWebsites/WalletRow.js#L140)

2022-02-28 08:41 UTC, AhmedIbrahim336 requested changes

2022-02-28 08:41 UTC, AhmedIbrahim336 commented on packages/yoroi-extension/app/ergo-connector/components/signin/SignTxPage.js
> +              ) : null}
Should display the placeholder image here as well

2022-02-28 08:41 UTC, AhmedIbrahim336 commented on packages/yoroi-extension/app/ergo-connector/components/signin/SignTxTabs.js
> +      label: 'UTXO addresses',
This should be added to `intl` as well.

2022-02-28 10:31 UTC, vsubhuman commented
@AhmedIbrahim336 , please add the fixes for the comments you have left

2022-03-01 12:47 UTC, AhmedIbrahim336 approved these changes
LGTM

2022-03-01 13:14 UTC, AhmedIbrahim336 commented
@Nebyt  review it carefully as Pual deleted some of our style files :)

2022-03-03 09:45 UTC, Nebyt requested changes
Several issues should be fixed:
- [ ] [The page is shifted up](https://app.asana.com/0/1201126389914030/1201907324853858)
- [ ] [Scroll is missed on the signing page](https://app.asana.com/0/1201126389914030/1201907324853865)
- [x] [Fix dApp connector layout on large screens, again](https://app.asana.com/0/1201126389914030/1201907324853872)

2022-03-04 14:34 UTC, Nebyt approved these changes
Checked. :+1:

2022-03-05 09:15 UTC, merged