Reduce complexity of the connectorStore
Emurgo/yoroi-frontend pull request #2779
Opened 2022-03-20 17:35 UTC by AhmedIbrahim336

2022-04-27 16:20 UTC, yushih requested changes
Please don't change `package-lock.json` when `package.json` is not changed.

2022-04-27 16:20 UTC, yushih commented on packages/yoroi-extension/app/ergo-connector/utils/connectorMessenger.js
> +              response => {
Please fix inconsistent indentations of this line and the previous.

Please use 2 space indentations for this file for consistency.

2022-04-27 16:37 UTC, yushih commented on packages/yoroi-extension/app/ergo-connector/utils/connectorMessenger.js
> +                }
I think there should be a `return` here.

2022-04-27 16:38 UTC, yushih commented on packages/yoroi-extension/app/ergo-connector/utils/connectorMessenger.js
> +                }
I think there should be a `return` here.

2022-04-27 16:43 UTC, yushih commented on packages/yoroi-extension/app/ergo-connector/utils/connectorMessenger.js
> +    }
Not wrong but the purpose of `new Promise` is to wrap a callback-styled function like `window.chrome.runtime.sendMessage` into a promise. Since `this._sendMessage` is already a promise, what's the point of using `new Promise`? (Also apply to functions below this).

2022-10-14 10:36 UTC, AhmedIbrahim336 commented
This PR is outdated. Looking into a new solution!

2022-10-14 10:36 UTC, closed without merging