Update "FAQ page" to be a hyperlink in the "Overview reward" popup
Emurgo/yoroi-frontend pull request #2845
Opened 2022-05-09 12:09 UTC by AhmedIbrahim336

the FAQ link should go to https://emurgohelpdesk.zendesk.com/

2022-06-01 04:41 UTC, yushih requested changes

2022-06-01 04:41 UTC, yushih commented on packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/OverviewDialog.js
> +      '!!!If the Reward amount is different than expected, see possible reasons of that on our',
Please change the string to:
```
'!!!If the Reward amount is different than expected, see possible reasons of that on our {faqLink}'
```
and handle it the same way `app/components/settings/categories/SupportSettings.js` handles `faqContent`.

2022-06-01 04:41 UTC, yushih commented on packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/OverviewDialog.js
> +                  <Link
Please do not concatenate parts into a sentence like this, because not all natural languages have the same grammatical structure like English.

2022-06-01 04:41 UTC, yushih commented on packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/OverviewDialog.js
> +                  <Link
Use `<FormattedMessage ... />` instead.

2022-06-02 03:27 UTC, yushih approved these changes

2022-06-02 03:27 UTC, yushih commented
/check

2022-06-02 03:27 UTC, yushih approved these changes

2022-06-02 04:43 UTC, yushih requested changes
Fix flow please @AhmedIbrahim336

2022-06-03 10:38 UTC, yushih commented
/check

2022-06-03 10:38 UTC, yushih approved these changes

2022-06-03 10:50 UTC, yushih requested changes
@AhmedIbrahim336 fix flow please

2022-06-04 14:50 UTC, vsubhuman reviewed
/check

2022-06-04 16:27 UTC, AhmedIbrahim336 commented
> @AhmedIbrahim336 fix flow please

Sorry, Just fixed it

2022-06-06 10:21 UTC, yushih approved these changes

2022-06-06 10:44 UTC, merged