Yoroi short term improvement pt.1
Emurgo/yoroi-frontend pull request #2856
Opened 2022-05-24 11:35 UTC by AhmedIbrahim336

# Changes 
1. [Change Summary Page Layout](https://emurgo.atlassian.net/jira/software/c/projects/YOEXT/boards/9?modal=detail&selectedIssue=YOEXT-154)
2. [Add skeleton loader to the dashboard page](https://emurgo.atlassian.net/jira/software/c/projects/YOEXT/boards/9?modal=detail&selectedIssue=YOEXT-153)
3. [Add the Support button ](https://emurgo.atlassian.net/jira/software/c/projects/YOEXT/boards/9?modal=detail&selectedIssue=YOEXT-155)
4. [Add FAQ external button to the left side navigation](https://emurgo.atlassian.net/jira/software/c/projects/YOEXT/boards/9?modal=detail&selectedIssue=YOEXT-156)

# Screenshots 
<img width="1440" alt="Screen Shot 2022-05-24 at 1 34 11 PM" src="https://user-images.githubusercontent.com/72753578/170025451-fbd2f243-ae62-4afd-9814-33f55a6fffaf.png">

<img width="1440" alt="Screen Shot 2022-05-24 at 1 34 35 PM" src="https://user-images.githubusercontent.com/72753578/170025402-e2f7a0e3-96d3-4567-955c-e047e239e80d.png">

2022-05-25 12:43 UTC, Nebyt approved these changes
:superhero:

2022-05-30 10:22 UTC, yushih requested changes
Please change Support.js so that no script is loaded from outside source. Please render the button with our own code and when the button is pressed, pop-up an iframe with the contents from zendesk.

2022-05-30 10:22 UTC, yushih commented on packages/yoroi-extension/app/components/widgets/Support.js
> +      const interval = setInterval(()=>{
Why not use setTimeout?

2022-05-30 10:22 UTC, yushih commented on packages/yoroi-extension/app/styles/context/layout.js
> +// import { ReactComponent as SupportIcon } from '../../assets/images/support.svg'
Please remove this change

2022-05-30 10:22 UTC, yushih commented on packages/yoroi-extension/app/components/widgets/Support.js
> +  }
No. We can't do this. We are a wallet!

2022-05-30 10:22 UTC, yushih commented on packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
> +  +purpose?: 'allWallets' | 'topBar',
Please make this non-optional and do not relying on default value.

2022-05-30 10:23 UTC, yushih commented on packages/yoroi-extension/app/components/widgets/Support.js
> +      const interval = setInterval(()=>{
Never mind. We shouldn't do this anyway.

2022-05-30 14:44 UTC, AhmedIbrahim336 commented on packages/yoroi-extension/app/components/widgets/Support.js
> +      const interval = setInterval(()=>{
Normally when the Zendesk script got loaded the **popup** opens automatically. to disable this behavior I need to check and hide it.

2022-05-30 14:45 UTC, AhmedIbrahim336 commented
@yushih  I fixed all of the required changes so far except for loading the Zendesk JS script.

2022-05-30 15:12 UTC, yushih commented
/check

2022-05-30 15:12 UTC, yushih approved these changes

2022-05-30 15:31 UTC, merged