Added functions to call signData api and 1 test
Emurgo/yoroi-frontend pull request #2889
Opened 2022-06-10 22:57 UTC by cmerloglb

2022-06-14 14:52 UTC, cmerloglb reviewed
/check

2022-06-14 14:54 UTC, cmerloglb reviewed
/check

2022-06-14 16:09 UTC, cmerloglb reviewed
/check

2022-06-14 17:27 UTC, cmerloglb reviewed
/check

2022-06-15 10:54 UTC, Nebyt requested changes
I sent in slack all changes necessary to make

2022-06-22 12:34 UTC, cmerloglb reviewed
/check

2022-06-22 13:10 UTC, cmerloglb reviewed
/check

2022-06-22 14:19 UTC, cmerloglb reviewed
/check

2022-06-22 14:49 UTC, cmerloglb reviewed
/check

2022-06-24 14:42 UTC, Nebyt requested changes

2022-06-24 14:42 UTC, Nebyt commented on packages/yoroi-extension/features/connector-anonymous-wallet-errors-checking.feature
> +  Scenario: dApp, anonymous wallet, unused adress, signing data, cancel signing
Misprint 'adress' instead of 'address'

2022-06-24 14:42 UTC, Nebyt commented on packages/yoroi-extension/features/mock-dApp-webpage/index.js
> +    await this.driver.executeScript(() => {
Add logging here, please

2022-06-24 14:42 UTC, Nebyt commented on packages/yoroi-extension/features/mock-dApp-webpage/index.js
> +    await this.driver.executeScript(() => {
Add logging here, please

2022-06-24 14:42 UTC, Nebyt commented on packages/yoroi-extension/features/mock-dApp-webpage/index.js
> +            callback({ success: false, errMsg: 'No unused addresses' });
Change please the `errMsg` to "No addresses found"

2022-06-24 14:42 UTC, Nebyt commented on packages/yoroi-extension/features/mock-dApp-webpage/index.js
> +      this.logger.info(`MockDApp: Using used address`);
Please, change the log message to `MockDApp: -> Using the address ${address}`

2022-06-24 14:42 UTC, Nebyt commented on packages/yoroi-extension/features/mock-dApp-webpage/index.js
> +      throw new MockDAppWebpageError('No Unused Addresses');
Please, change the error message to `There are no addresses to proceed`

2022-06-24 14:59 UTC, cmerloglb reviewed
/check

2022-06-24 15:11 UTC, Nebyt approved these changes

2022-06-24 15:49 UTC, Nebyt reviewed
/check

2022-06-24 16:48 UTC, merged