Trezor emu controler
Emurgo/yoroi-frontend pull request #2908
Opened 2022-07-05 06:30 UTC by Nebyt

Added the trezor emulator controller to work with the trezor emulator run from the [trezor-user-env](https://github.com/trezor/trezor-user-env)

2022-07-05 13:37 UTC, cmerloglb approved these changes

2022-07-11 13:01 UTC, yushih requested changes
Really awesome work! But could you also fix the Trezor tests with the "mock Trezor lib" in dashboard.feature, hardware.feature and yoroi-transfer.feature? Thanks.

2022-07-11 13:01 UTC, yushih commented on packages/yoroi-extension/app/api/ada/lib/state-fetch/mockNetwork.js
> +  return async _ => ({});
There are lots of formatting changes making it hard to see which are non-syntactical changes. Could you please include only "real" changes in this PR and open another PR for re-formatting only? Thanks!

2022-07-11 13:01 UTC, yushih commented on packages/yoroi-extension/features/mock-chain/mockCardanoImporter.js
> +// eslint-disable-next-line import/named
why do we need this?

2022-07-11 13:01 UTC, yushih commented on packages/yoroi-extension/features/mock-chain/mockCardanoServer.js
> +      const result = mockImporter.getUtxoData(req.params.txHash, Number(req.params.txIndex));
Please include only "real" changes. Thanks.

2022-07-11 13:01 UTC, yushih commented on packages/yoroi-extension/webpack/commonConfig.js
> +  alias: (networkName === 'test' && emulator === false)
I guess we can get rid of the alias for `'trezor-connect'` and also `@emurgo/ledger-connect-handler` ( I should've done it when merging ledger code but forgot), so that `alias` is always `{ process: 'process/browser',}`.

2022-07-11 13:01 UTC, yushih commented on packages/yoroi-extension/webpack/commonConfig.js
> +  emulator /*: boolean */,
Is it for future use? Currently, the function is not using this parameter at all so why pass it in?

2022-07-20 10:27 UTC, closed without merging