Separate browser logs
Emurgo/yoroi-frontend pull request #2977
Opened 2022-08-24 20:45 UTC by cmerloglb

2022-08-24 20:46 UTC, cmerloglb reviewed
/check

2022-08-25 10:14 UTC, Nebyt requested changes
# Required changes:

1. The structure of logs should be like this:

- testRunsData_<browser>
  - testsLogs
    - testLogs
    - ...
  - mockAndWMLogs
  - trezorEmulatorLogs
  - webDriverLogs

2. Remove creating the old tests logs directory in the `BeforeAll` hook
3. If you rerun the same test locally you receive the error 
```
file already exists, mkdir './testRunsData_cardanoMockServerLogs'

4. Removed unused variables in constants
5. Move creating loggers into the first `Before` hook. It give us readable names for logs

2022-08-25 14:21 UTC, Nebyt reviewed
/check

2022-08-25 18:19 UTC, Nebyt approved these changes

2022-09-14 07:25 UTC, merged