Reduce code duplication in the `connectorStore`
Emurgo/yoroi-frontend pull request #3019
Opened 2022-10-18 11:28 UTC by AhmedIbrahim336

Jira: [Connector Store refractory](https://emurgo.atlassian.net/browse/YOEXT-67)

2022-11-16 09:28 UTC, yushih requested changes
`DappConnectorStore` should be in `stores/toplevel` like the others.

2022-11-16 09:28 UTC, yushih commented on packages/yoroi-extension/app/ergo-connector/stores/ConnectorStore.js
> +          reject(`Could not establish connection: ${JSON.stringify(typeof message === 'object' ? message : '')}`);
should `return` after `reject` because only either one of `reject` or `resolve` should be called.

2022-11-16 09:28 UTC, yushih commented on packages/yoroi-extension/app/stores/DappConnectorStore.js
> +async function sendMsgConnect(): Promise<?ConnectingMessage> {
The `_getConnectingMsg` function in this file is not used at all and should be removed. And since it is the only caller of `sendMsgConnect`,  `sendMsgConnect` and `initedConnecting` should be removed too.

2022-11-23 13:06 UTC, AhmedIbrahim336 commented on packages/yoroi-extension/app/stores/DappConnectorStore.js
> +async function sendMsgConnect(): Promise<?ConnectingMessage> {
Done

2022-11-23 13:07 UTC, AhmedIbrahim336 commented
> `DappConnectorStore` should be in `stores/toplevel` like the others.

Nice catch. I moved it

2022-12-07 21:41 UTC, vsubhuman approved these changes

2022-12-08 07:04 UTC, vsubhuman reviewed
/check

2022-12-09 07:16 UTC, vsubhuman reviewed
/check

2022-12-09 13:57 UTC, vsubhuman reviewed
/check

2022-12-09 14:20 UTC, merged