Implement the new Revamp designs for the add wallet page
Emurgo/yoroi-frontend pull request #3125
Opened 2023-02-20 12:29 UTC by AhmedIbrahim336

2023-02-20 13:24 UTC, nistadev requested changes

2023-02-20 13:24 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/add-wallet-revamp/AddWalletCard.js
> +export default class AddWalletCard extends Component<Props> {
I think we better use a functional component here

2023-02-20 13:24 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/add-wallet-revamp/AddWalletPageContent.js
> +export default class AddWalletPageContent extends Component<{||}> {
Use a functional component and add `injectIntl`

2023-02-20 13:24 UTC, nistadev commented on packages/yoroi-extension/app/containers/wallet/AddWalletPageRevamp.js
> +export default class AddWalletPageRevamp extends Component {
Use functional component

2023-02-20 13:24 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/add-wallet-revamp/AddWalletPageHeader.js
> +export default class AddWalletPageHeader extends Component<{||}> {
Use functional component

2023-02-25 17:13 UTC, a-hosani approved these changes

2023-02-25 20:16 UTC, AhmedIbrahim336 commented
[autoscirpt] Jira Ticket: **[implement the new Revamp designs for the add wallet page](https://emurgo.atlassian.net/browse/YOEXT-524)**

[](__JIRA_COMMENT_FLAG)

2023-03-06 23:00 UTC, a-hosani approved these changes

2023-03-07 14:00 UTC, Nebyt approved these changes
Checked. :+1:

2023-03-09 11:54 UTC, nistadev requested changes

2023-03-09 11:54 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/add-wallet-revamp/AddWalletCard.js
> +export default function AddWalletCard(props: Props): Node {
Add wallet card seems not to fit into a generic component. We use this type of card on other funnels, eg. Restore. I think we should change the name and structure to fit this more generic purpose.

2023-04-07 12:20 UTC, vsubhuman approved these changes

2023-04-07 12:45 UTC, merged