feat: format big numbers using `Intl` api when rendered on screen
Emurgo/yoroi-frontend pull request #3171
Opened 2023-04-18 22:49 UTC by neuodev

Format token amount: `100000` ==> `100,000` 

<details><summary>Screenshot</summary>
<p>

![Screenshot 2023-04-19 at 12 45 26 AM](https://user-images.githubusercontent.com/72753578/232921423-de7b6178-b52e-400f-bc2b-69da1856a152.png)
![Screenshot 2023-04-19 at 12 47 08 AM](https://user-images.githubusercontent.com/72753578/232921426-a5ba6f05-425d-4e51-aecb-83f5b33a2444.png)

</p>
</details>

2023-04-18 22:49 UTC, neuodev commented
[autoscript] ⚠️ `Ahmed/format-nums` doesn't full our branch naming convention.
Should follow `<tag>/<jira-ticket-id>/<short-name>`
<details>
<summary>Details</summary>

- `<tag>`: `fix`, `feat`, `chore`, `refactor`, `test`, ...
- `<jira-ticket-id>`: The issue ID of JIRA all capital letters
- `<short-name>`: A short and descriptive name for the branch
</details>

[](__JIRA_COMMENT_FLAG)

2023-04-18 22:50 UTC, neuodev commented
Note: the big diff is because of the formatted file that was not formated

2023-04-19 10:30 UTC, vsubhuman requested changes
@neuodev , plz check the comment about the locale and also please roll back the formatting changes that are not related to the intended change, it becomes very hard to review and make sure I don't miss any of the changes that are actually important in the PR.

We can have formatting fixes as separate PRs that are not intended to have any logic changes.

2023-04-19 10:30 UTC, vsubhuman commented on packages/yoroi-extension/app/components/wallet/assets/TokenList.js
> +        <Typography fontWeight="500">{new Intl.NumberFormat().format(amount)}</Typography>
@neuodev , the number format must be dependent on the selected language. The formatting of the numbers must be matching the selected locale, for now. Later we might think on having it as a separate option, but not right now.

Make sure you resolve the currently selected language and pass it into the `NumberFormat` constructor.

2023-06-05 13:29 UTC, neuodev commented on packages/yoroi-extension/app/components/wallet/assets/TokenList.js
> +        <Typography fontWeight="500">{new Intl.NumberFormat().format(amount)}</Typography>
@vsubhuman Fixed! I used our stander way of formating amounts

2023-06-16 12:53 UTC, vsubhuman approved these changes

2023-06-16 13:27 UTC, merged