Feat/yoext 527/restore wallet revamp
Emurgo/yoroi-frontend pull request #3175
Opened 2023-04-20 09:24 UTC by nistadev

<details>
<summary>Selection page</summary>
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/22194171/233320437-3fd0825a-3f43-4edd-be63-f8ac10d928c4.png">
</details>

<details>
<summary>Network selection (if not production)</summary>
<img width="943" alt="image" src="https://user-images.githubusercontent.com/22194171/233320596-874979b2-3cbe-460b-ad65-b34e03feb3bb.png">
</details>

<details>
<summary>Wallet type</summary>
<img width="752" alt="image" src="https://user-images.githubusercontent.com/22194171/233320748-97ec58db-3a9d-422f-ac32-e42d4cd3d09f.png">
</details>

<details>
<summary>15/24-word screens</summary>
<img width="826" alt="image" src="https://user-images.githubusercontent.com/22194171/233320853-dfae72ea-b814-498d-aa50-c007cef0148c.png">
<img width="944" alt="image" src="https://user-images.githubusercontent.com/22194171/233321009-55e688ed-4923-4284-97ce-67eadf82850c.png">
</details>

<details>
<summary>Input styles</summary>
<img width="289" alt="image" src="https://user-images.githubusercontent.com/22194171/233321218-ead55ef4-2e40-4b40-bd5f-5a394b18d851.png">
<img width="338" alt="image" src="https://user-images.githubusercontent.com/22194171/233321314-411bcd68-1784-478d-8efc-1a2e5daa067b.png">
<img width="676" alt="image" src="https://user-images.githubusercontent.com/22194171/233321441-790c4122-5004-4821-94dc-f2f2324ad72e.png">
</details>

<details>
<summary>Duplicated Wallet dialog</summary>
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/22194171/233321570-28953969-81ef-4bcf-bc41-fae4401d1e5e.png">
</details>

<details>
<summary>Wallet details screen</summary>
<img width="698" alt="image" src="https://user-images.githubusercontent.com/22194171/233321949-d2e3d0ae-a710-451f-8b65-84d3bf58b74c.png">
</details>

2023-04-20 09:24 UTC, neuodev commented
[autoscirpt] Jira Ticket: **[Implementation of the Create & Restore funnels designs](https://emurgo.atlassian.net/browse/YOEXT-527)**

[](__JIRA_COMMENT_FLAG)

2023-04-21 15:57 UTC, vsubhuman approved these changes

2023-04-21 17:03 UTC, vsubhuman requested changes
@nistadev , fix all eslint errors: https://github.com/Emurgo/yoroi-frontend/actions/runs/4766649790/jobs/8473941285?pr=3175

2023-04-24 12:30 UTC, vsubhuman reviewed
/check

2023-04-24 13:16 UTC, merged