fix: add `Intl` & layout fixes for the connected dApps page
Emurgo/yoroi-frontend pull request #3205
Opened 2023-05-13 16:44 UTC by neuodev

2023-05-13 16:44 UTC, neuodev commented
[autoscirpt] Jira Ticket: **[Long dApp URL causes the layout to be broken](https://emurgo.atlassian.net/browse/YOEXT-601)**

[](__JIRA_COMMENT_FLAG)

2023-05-15 12:01 UTC, zuzunker requested changes
@neuodev , plz roll back any code-style diff not related to the functional change in the PR, it is greatly complicating the review process. If you want to, you can make a separate PR with style fixes, but then it should have no functional changes at all. /check

2023-05-19 10:55 UTC, Nebyt approved these changes

2023-05-19 11:58 UTC, vsubhuman approved these changes

2023-05-19 12:14 UTC, merged

2023-05-22 04:36 UTC, neuodev commented
> @neuodev , plz roll back any code-style diff not related to the functional change in the PR, it is greatly complicating the review process. If you want to, you can make a separate PR with style fixes, but then it should have no functional changes at all. /check

Sorry, just saw your comment! nice idea about a specific PR for formatting changes! Will make one if needed!