remove ergo and paper options in create/restore
Emurgo/yoroi-frontend pull request #3215
Opened 2023-05-19 17:54 UTC by vsubhuman

2023-05-19 17:54 UTC, neuodev commented
[autoscript] ⚠️ `ruslan/remove-ergo-and-paper-options` doesn't full our branch naming convention.
Should follow `<tag>/<jira-ticket-id>/<short-name>`
<details>
<summary>Details</summary>

- `<tag>`: `fix`, `feat`, `chore`, `refactor`, `test`, ...
- `<jira-ticket-id>`: The issue ID of JIRA all capital letters
- `<short-name>`: A short and descriptive name for the branch
</details>

[](__JIRA_COMMENT_FLAG)

2023-05-19 17:59 UTC, vsubhuman reviewed
/check

2023-05-20 07:53 UTC, neuodev commented on packages/yoroi-extension/features/step_definitions/wallet-creation-steps.js
>  });
Empty test block! Is done on purpose?
```suggestion
```

2023-05-20 15:33 UTC, Nebyt commented on packages/yoroi-extension/features/step_definitions/wallet-creation-steps.js
>  });
Looks like I forget to delete it :face_in_clouds:

2023-05-20 15:41 UTC, Nebyt requested changes
@vsubhuman Please rollback changes from the folder `../packages/yoroi-extension/features`. I will remove outdated info myself.

2023-05-22 16:47 UTC, vsubhuman reviewed
@Nebyt , `/features` content is rolled back, /check now plz

2023-05-22 18:52 UTC, Nebyt approved these changes

2023-05-22 19:38 UTC, merged