Feat/yoext 681/revamp dapp connections
Emurgo/yoroi-frontend pull request #3275
Opened 2023-08-30 21:56 UTC by nistadev

**Screenshots**

_No Dapps_
<img width="1399" alt="image" src="https://github.com/Emurgo/yoroi-frontend/assets/22194171/78f96d29-d56a-4513-bb4d-08f1e246cdea">

_With Dapps_
<img width="1399" alt="image" src="https://github.com/Emurgo/yoroi-frontend/assets/22194171/01efa643-8502-4641-a7d4-a71c30b5eb51">

_Dapp hover_
<img width="1400" alt="image" src="https://github.com/Emurgo/yoroi-frontend/assets/22194171/27975fa5-6b20-423f-a397-0b0ba70a6093">

2023-08-30 21:57 UTC, neuodev commented
[autoscirpt] Jira Ticket: **[Connected DApps Page](https://emurgo.atlassian.net/browse/YOEXT-681)**

[](__JIRA_COMMENT_FLAG)

2023-09-21 08:17 UTC, neuodev requested changes
Wallet information is missing. 

![Screenshot 2023-09-21 at 11 16 39 AM](https://github.com/Emurgo/yoroi-frontend/assets/72753578/816c12ac-13f8-4153-8630-da0ad6afb61e)

2023-09-21 08:17 UTC, neuodev commented on packages/yoroi-extension/app/components/dapp-connector/ConnectedWebsites/ConnectedWebsitesPage.js
> +import { ReactComponent as NoItemsFoundImg } from '../../../assets/images/dapp-connector/no-websites-connected.inline.svg';
```suggestion
import { ReactComponent as NoDappsFoundImg } from '../../../assets/images/dapp-connector/no-dapps-connected.inline.svg';
```

2023-09-21 08:17 UTC, neuodev commented on packages/yoroi-extension/app/components/dapp-connector/ConnectedWebsites/ConnectedWebsitesPage.js
> +    defaultMessage: '!!!Connected DApps ({numDapps})',
```suggestion
    defaultMessage: '!!!Connected DApps ({dappsCount})',
```

2023-09-21 08:17 UTC, neuodev commented on packages/yoroi-extension/app/i18n/locales/en-US.json
> +  "connector.connected-dapps.title": "Connected DApps ({numDapps})",
```suggestion
  "connector.connected-dapps.title": "Connected DApps ({dappsCount})",
```

2023-09-21 08:33 UTC, neuodev commented
> Wallet information is missing.
> 
> ![Screenshot 2023-09-21 at 11 16 39 AM](https://user-images.githubusercontent.com/72753578/269541607-816c12ac-13f8-4153-8630-da0ad6afb61e.png)

Fixed 👇 

<details><summary>Preview</summary>
<p>

![Screenshot 2023-09-21 at 11 31 15 AM](https://github.com/Emurgo/yoroi-frontend/assets/72753578/d3de8b8c-3d28-439d-b4d5-3185d1285dc0)


</p>
</details>

2023-09-21 08:42 UTC, neuodev commented
Note: flow errors in this PR are caused by the "target" branch. should be fixed their first.

2023-09-21 08:42 UTC, neuodev approved these changes

2023-10-07 21:35 UTC, vsubhuman approved these changes

2023-10-08 08:28 UTC, vsubhuman reviewed
/check

2023-10-08 18:52 UTC, merged