add swap page with tabs
Emurgo/yoroi-frontend pull request #3277
Opened 2023-09-05 11:14 UTC by nistadev

**Screenshots**
<img width="1297" alt="image" src="https://github.com/Emurgo/yoroi-frontend/assets/22194171/0d0e2170-2f73-4d09-92e8-2e8a3db9fd66">

2023-09-05 11:14 UTC, neuodev commented
[autoscirpt] Jira Ticket: **[Create the SWAP page in revamp with two empty tabs and it should be available only in dev mode for now](https://emurgo.atlassian.net/browse/YOEXT-647)**

[](__JIRA_COMMENT_FLAG)

2023-09-21 09:11 UTC, neuodev requested changes

2023-09-21 09:11 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/SwapPageContainer.js
> +|};
Empty line please 🙂 
```suggestion
|};

```

2023-09-21 09:11 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/categories/OrdersPage.js
> +  }
All these values are not needed. I think you didn't do it on purpose. You forgot to delete it. 

```suggestion
  @computed get generated(): {|
    actions: {||},
    stores: {||},
  |} {
    if (this.props.generated !== undefined) {
      return this.props.generated;
    }
    if (this.props.stores == null || this.props.actions == null) {
      throw new Error(`${nameof(SwapOrdersPage)} no way to generated props`);
    }    
    return Object.freeze({
      stores: {},
      actions: {},
    });
  }
```

2023-09-21 09:11 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/categories/OrdersPage.js
> +
Not all these imports are needed. Please include only needed imports.

2023-09-21 09:11 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/categories/OrdersPage.js
> +      canRegisterProtocol: environment.userAgentInfo.canRegisterProtocol,
Please remove these stores and actions as you don't need them.

2023-09-21 09:11 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/categories/SwapPage.js
> +  @computed get generated(): {|
Should be deleted as well.

2023-11-19 13:17 UTC, vsubhuman commented on packages/yoroi-extension/.flowconfig
> +include_warnings=true
```suggestion
include_warnings=false
```

2023-11-19 13:17 UTC, vsubhuman submitted a review, later dismissed

2023-11-21 08:28 UTC, merged