Feat/yoext 650/swap input fields
Emurgo/yoroi-frontend pull request #3286
Opened 2023-09-14 11:30 UTC by nistadev

**Screenshots**

<img width="600" alt="image" src="https://github.com/Emurgo/yoroi-frontend/assets/22194171/2efd0c47-fbad-4c36-a748-a1398ee9d7e4">

2023-09-14 11:30 UTC, neuodev commented
[autoscirpt] Jira Ticket: **[[swap] Create the "From" and "To" field component](https://emurgo.atlassian.net/browse/YOEXT-650)**

[](__JIRA_COMMENT_FLAG)

2023-09-18 11:03 UTC, neuodev commented on packages/yoroi-extension/app/components/swap/SwapInput.js
> +            Current balance: {amount} {ticker}
Please use `Intl`

2023-09-18 11:04 UTC, nistadev commented on packages/yoroi-extension/app/components/swap/SwapInput.js
> +            Current balance: {amount} {ticker}
Rn is only for display purposes for the demo, will add intl later on to not block the components development

2023-09-21 09:32 UTC, neuodev requested changes

2023-09-21 09:32 UTC, neuodev commented on packages/yoroi-extension/app/components/swap/PriceInput.js
> +export default function PriceInput({ label, assets = [], readonly, isLoading }) {
Missing types. 
```suggestion

type Props = {|
  label: string,
  assets:  Assets[], 
  readonly?: boolean,
  isLoading?: boolean,
|};

export default function PriceInput({ label, assets = [], readonly, isLoading }) {
```

2023-09-21 09:32 UTC, neuodev commented on packages/yoroi-extension/app/components/swap/PriceInput.js
> +          <Box>{asset2.ticker}</Box>
I can see you only need the "assets ticker" so you don't need the whole "asset" object. **Component should have access to just what it needs**. 

Also, let's improve the terminology a little bit. For example, for the currency “USDA/ADA”, USDA is the base currency and ADA is the quote currency.

```suggestion
          <Box>{base}</Box>
          <Box>/</Box>
          <Box>{quote}</Box>
```

2023-09-21 09:32 UTC, neuodev commented on packages/yoroi-extension/app/components/swap/SwapInput.js
> +export default function SwapInput({
Please add type definitions.

2023-09-21 09:32 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/categories/SwapPage.js
> +      {/* From Field */}
```suggestion
```

2023-09-21 09:32 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/categories/SwapPage.js
> +      {/* Clear and switch */}
```suggestion

```

2023-09-21 09:32 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/categories/SwapPage.js
> +      {/* To Field */}
```suggestion

```

2023-09-21 09:32 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/categories/SwapPage.js
> +      {/* Price between assets */}
```suggestion

```

2023-09-21 09:32 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/categories/SwapPage.js
> +          label="Market price"
I would suggest using this props structure instead. 

```suggestion
          baseAsset={{ ticker: 'TADA', amount: 20 }}
          quoteAsset={{ ticker: 'USDA', amount: 5 }}
          readonly={isMarketOrder}
          label="Market price"
```

2023-09-21 09:32 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/categories/SwapPage.js
> +      {/* Slippage settings */}
```suggestion

```

2023-09-21 09:32 UTC, neuodev commented on packages/yoroi-extension/app/containers/swap/categories/SwapPage.js
> +      {/* Available pools */}
```suggestion

```

2023-10-20 10:44 UTC, nistadev commented
Closing for this: https://github.com/Emurgo/yoroi-frontend/pull/3320

2023-10-20 10:44 UTC, closed without merging