Chore/yoext 940/eliminate warnings
Emurgo/yoroi-frontend pull request #3365
Opened 2023-12-11 10:25 UTC by yushih

Many warnings are due to block elements nested inside `<p>`. So replace`<p>` by `<div>`. Also add `component="div"` to `<Typography>` to avoid generating `<p>`.

2023-12-11 10:25 UTC, neuodev commented
[autoscirpt] Jira Ticket: **[Get rid of some console warnings](https://emurgo.atlassian.net/browse/YOEXT-940)**

[](__JIRA_COMMENT_FLAG)

2023-12-11 12:17 UTC, nistadev requested changes
Overall looks good, nothing critical. I would use `span` instead of `div` on `Typoghaphy` components tho.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/profile/nightly/NightlyForm.js
> +                <Typography component="div" component="li" variant="body1" lineHeight="24px">
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/profile/nightly/NightlyForm.js
> +                <Typography component="div" component="li" variant="body1" lineHeight="24px">
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/profile/nightly/NightlyForm.js
> +                <Typography component="div" component="li" variant="body1" lineHeight="24px">
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/profile/nightly/NightlyForm.js
> +                <Typography component="div" component="li" variant="body1" lineHeight="24px">
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/settings/categories/SupportSettings.js
> +          <Typography component="div" component="h5" variant="h5" mb="24px" color="common.black" fontWeight={500}>
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/settings/categories/general-setting/AboutYoroiSettingsBlock.js
> +        <Typography component="div" component="h2" variant="body1" fontWeight={500} mb="16px" color="grayscale.900">
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/settings/categories/general-setting/UnitOfAccountSettings.js
> +        <Typography component="div"
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/swap/SelectPoolDialog.js
> +                <Typography component="div" component="span" variant="body1" fontWeight={500}>
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/swap/SelectPoolDialog.js
> +                <Typography component="div" component="span" variant="body1">
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/swap/SelectPoolDialog.js
> +                <Typography component="div" component="span" variant="body1">
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/WalletReceiveRevamp.js
> +      <Typography component="div" component="h2" variant="body2" color="grayscale.500" textAlign="right">
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/assets/NFTDetails.js
> +                      <Typography component="div" as="span" display="flex">
Use rather `component="div"` or `component="span"`

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/assets/NFTDetails.js
> +              <Typography component="div" component="pre" variant="body3" lineHeight="22px" fontFamily="monospace">
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/DelegatedStakePoolCard.js
> +            <Typography component="div" as="span" fontWeight={500} color="grayscale.max" variant="h2">
User rather `component="div"` or `span`.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/DelegatedStakePoolCard.js
> +            <Typography component="div" as="span" fontWeight={500} color="grayscale.max" variant="h2">
Use rather `component="div"` or `span`.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/DelegatedStakePoolCard.js
> +            <Typography component="div" as="span" fontWeight={500} color="grayscale.max" variant="h2">
Use rather `component="div"` or `span`.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/summary/WalletSummaryRevamp.js
>              as="p"
Remove `as="p"`.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/transactions/TransactionRevamp.js
> +        <Typography component="div" as="span" fontWeight="inherit" fontSize="inherit">
Use rather `component="div"` or span.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/transactions/TransactionRevamp.js
> +              <Typography component="div" as="span" fontWeight="inherit" fontSize="inherit">
Use rather `component="div"` or `span`.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/components/wallet/transactions/TransactionRevamp.js
> +        <Typography component="div" as="span" fontSize="inherit">
Use rather `component="div"` or `span`.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/connector/components/signin/UtxoDetails.js
> +            <Typography component="div" as="span" color="var(--yoroi-palette-gray-600)">
Use rather `component="div"` or `span`.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/connector/components/signin/cardano/UtxoDetails.js
> +            <Typography component="div" as="span" color="#242838">
Use rather `component="div"` or `span`.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/containers/wallet/dialogs/RevampAnnouncementDialog.js
> +                  <Typography component="div" component="li" variant="body1" color="grayscale.900">
Remove `component="div"` since we have another component defined.

2023-12-11 12:17 UTC, nistadev commented on packages/yoroi-extension/app/containers/wallet/dialogs/RevampAnnouncementDialog.js
> +                  <Typography component="div" component="li" variant="body1" color="grayscale.900">
Remove `component="div"` since we have another component defined.

2023-12-12 16:36 UTC, yushih commented
@nistadev I added `component="div"` instead of `"span"` to `<Typography` that originally were rendered as `<p>` because `<p>` is a block element. If `<p>` is replaced by a `<span>` which is an inline element, the layout may be broken.

2023-12-14 08:34 UTC, Nebyt submitted a review, later dismissed
LGTM

2023-12-14 21:56 UTC, vsubhuman reviewed
/check

2023-12-14 22:19 UTC, vsubhuman reviewed
/check

2023-12-15 16:38 UTC, vsubhuman reviewed
/check

2023-12-15 16:54 UTC, merged