chore: update csl version
Emurgo/yoroi-frontend pull request #3405
Opened 2024-01-30 13:39 UTC by neuodev

2024-01-30 13:40 UTC, neuodev reviewed
/check

2024-01-30 13:40 UTC, neuodev commented
[autoscript] ⚠️ `ahmed/csl-new-ver` doesn't full our branch naming convention.
Should follow `<tag>/<jira-ticket-id>/<short-name>`
<details>
<summary>Details</summary>

- `<tag>`: `fix`, `feat`, `chore`, `refactor`, `test`, ...
- `<jira-ticket-id>`: The issue ID of JIRA all capital letters
- `<short-name>`: A short and descriptive name for the branch
</details>

[](__JIRA_COMMENT_FLAG)

2024-01-31 16:50 UTC, vsubhuman requested changes

2024-01-31 16:50 UTC, vsubhuman commented on packages/yoroi-extension/package.json
> +    "@emurgo/cross-csl-browser": "4.1.0",
Can't merge it just like that. We are now restricted to always using the matching cross-csl version with the `yoroi-eutxo-txs`. First a version of eutxo needs to be published that used cross-csl `4.1.0` and then we can update both eutxo and cross-csl together

2024-04-24 21:08 UTC, closed without merging