fix wrong password handling when changing password
Emurgo/yoroi-frontend pull request #3709
Opened 2024-10-23 18:11 UTC by yushih

2024-10-24 11:21 UTC, Nebyt submitted a review, later dismissed

2024-10-25 06:28 UTC, vsubhuman requested changes

2024-10-25 06:28 UTC, vsubhuman commented on packages/yoroi-extension/app/api/thunk.js
> +  if (resp?.error === 'Passphrase doesn\'t match') {
Unmagic

2024-10-29 11:08 UTC, yushih commented on packages/yoroi-extension/app/api/thunk.js
> +  if (resp?.error === 'Passphrase doesn\'t match') {
done

2024-10-29 11:32 UTC, vsubhuman approved these changes

2024-10-29 11:56 UTC, merged