Fix wrong password handling
Emurgo/yoroi-frontend pull request #3710
Opened 2024-10-23 18:17 UTC by yushih

2024-10-24 11:13 UTC, Nebyt submitted a review, later dismissed

2024-10-25 07:55 UTC, vsubhuman requested changes

2024-10-25 07:55 UTC, vsubhuman commented on packages/yoroi-extension/app/api/thunk.js
> +  if (typeof result.error === 'string' && result.error.includes('api.errors.IncorrectPasswordError')) {
Unmagic

2024-10-29 10:44 UTC, yushih commented on packages/yoroi-extension/app/api/thunk.js
> +  if (typeof result.error === 'string' && result.error.includes('api.errors.IncorrectPasswordError')) {
done

2024-10-29 12:41 UTC, vsubhuman approved these changes

2024-10-29 13:15 UTC, merged