Dark theme support: restore and create wallet
Emurgo/yoroi-frontend pull request #3714
Opened 2024-10-28 09:40 UTC by SorinC6

task: 
- https://emurgo.atlassian.net/browse/YOEXT-1316
- https://emurgo.atlassian.net/browse/YOEXT-1317

2024-10-29 09:15 UTC, SorinC6 reviewed
/check

2024-11-09 13:16 UTC, Nebyt requested changes
@SorinC6 please check and accept suggestions.

2024-11-09 13:16 UTC, Nebyt commented on packages/yoroi-extension/app/components/wallet/transactions/TransactionRevamp.js
> +  '& svg': {
```suggestion
  '& svg': {
    width: '48px',
    height: '48px',
```

2024-11-09 13:16 UTC, Nebyt commented on packages/yoroi-extension/app/components/wallet/transactions/TransactionRevamp.js
> +    <Box sx={{ width: 40, height: 40 }}>
```suggestion
    <Box sx={{ width: 48, height: 48 }}>
```

2024-11-09 13:16 UTC, Nebyt commented on packages/yoroi-extension/app/components/wallet/summary/WalletSummaryRevamp.js
> +              <Typography variant="body2" color="ds.text_gray_medium">
```suggestion
              <Typography variant="body2" color="ds.text_gray_low">
```

2024-11-09 13:16 UTC, Nebyt commented on packages/yoroi-extension/app/components/wallet/summary/WalletSummaryRevamp.js
> +              <Typography variant="body2" color="ds.text_gray_medium">
```suggestion
              <Typography variant="body2" color="ds.text_gray_low">
```

2024-11-09 13:16 UTC, Nebyt commented on packages/yoroi-extension/app/components/wallet/summary/WalletSummaryRevamp.js
> +            <Grid item xs={2} sx={{ textAlign: 'right' }} color="ds.text_gray_medium">
```suggestion
            <Grid item xs={2} sx={{ textAlign: 'right' }} color="ds.text_gray_low">
```

2024-11-09 13:16 UTC, Nebyt commented on packages/yoroi-extension/app/components/wallet/summary/WalletSummaryRevamp.js
> +            <Grid item xs={4} sx={{ textAlign: 'right', pr: '30px' }} color="ds.text_gray_medium">
```suggestion
            <Grid item xs={4} sx={{ textAlign: 'right', pr: '30px' }} color="ds.text_gray_low">
```

2024-11-09 13:16 UTC, Nebyt commented on packages/yoroi-extension/app/components/wallet/transactions/TransactionRevamp.js
> +const IconWrapper = styled(Box)(({ isDark, colors, theme }) => ({
```suggestion
const IconWrapper = styled(Box)(({ isDark, colors }) => ({
```

2024-11-26 12:27 UTC, SorinC6 reviewed
/check

2024-11-29 15:33 UTC, Nebyt reviewed
/check

2024-11-29 15:37 UTC, Nebyt approved these changes

2024-11-29 16:23 UTC, merged